 export const personalData=[
    {
        id: 'radio1',
        name: 'staffCourtesy',
         
        label: 'Staff courtesy and presentation',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio2',
        name: 'staffHygiene',
         
        label: 'Staff Personnel Hygiene',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio3',
        name: 'staffUniform',
         
        label: 'Uniforms, Shoes, Caps',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio4',
        name: 'staffTurnover',
         
        label: 'Staff Turnover, Absenteeism, Late Coming',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio5',
        name: 'staffKnowledge',
         
        label: 'Staff knowledge and responsiveness',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];

 export const cleaningandHygieneData=[
    {
        id: 'radio6',
        name: 'cleaningPremises',
         
        label: 'Cleaning of premises',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio7',
        name: 'cleaningToilets',
         
        label: 'Cleaning of Toilets',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio8',
        name: 'judiciousUseMaterial',
         
        label: 'Judicious use of Housekeeping material',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio9',
        name: 'documentationTasks',
         
        label: 'Documentation of tasks (todo & completed)',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio10',
        name: 'garbageDisposal',
         
        label: 'Suitable Garbage Disposal Measures',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ]

 export const siteSupervisionData=[
    {
        id: 'radio11',
        name: 'supervisionStandards',
         
        label: 'Supervision Standards',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio12',
        name: 'jobKnowledge',
         
        label: 'Job Knowledge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio13',
        name: 'speedEfficiencyWorkQuality',
         
        label: 'Speed, Efficiency, Work quality of site incharge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio14',
        name: 'responsivenessCustomerNeeds',
         
        label: 'Responsiveness To Customer Needs',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio15',
        name: 'endUserFeedback',
         
        label: 'End User Feedback',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];

 export const purchaseandStoresData=[
    {
        id: 'radio16',
        name: 'qualityRawMaterial',
         
        label: 'Quality of Raw Material',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio17',
        name: 'levelOfStocking',
         
        label: 'Level of Stocking',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio18',
        name: 'binCardDailyIndent',
         
        label: 'Bin Card, Daily Indent System Being Followed',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio19',
        name: 'purchaseSpecifications',
         
        label: 'Purchase Specifications Being Followed',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio20',
        name: 'qualityMaterialSupplied',
         
        label: 'Quality of Material Supplied',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];
export const controlsData=[
    {
        id: 'radio21',
        name: 'documentationBilling',
         
        label: 'Appropriate documentation and Billing',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio22',
        name: 'attendanceDocuments',
         
        label: 'Attendance and other relevant documents submitted on time',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio23',
        name: 'regularTrainings',
         
        label: 'Regular trainings held (on-site / off-site)',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio24',
        name: 'preventiveMaintenanceRecommendations',
         
        label: 'Recommendation on preventive maintenance',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio25',
        name: 'timelyReceiptOfMaterials',
         
        label: 'Timely receipt of materials',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
];

export const hoandTeamManagersData=[
    {
        id: 'radio26',
        name: 'managementTeamContact',
         
        label: 'Management team in regular contact',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio27',
        name: 'supervisionKnowledge',
         
        label: 'Supervision and Knowledge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio28',
        name: 'clientNeedsResponsiveness',
         
        label: 'Responsiveness to Client\'s Needs',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio29',
        name: 'newTechnologyRecommendations',
         
        label: 'Recommendation on new technology',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio30',
        name: 'timelyDocumentation',
         
        label: 'Provide timely documentation and information',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
];



