 export const personalData=[
    {
        id: 'radio1',
        name: 'personal1',
         
        label: 'Staff courtesy and presentation',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio2',
        name: 'personal2',
         
        label: 'Staff Personnel Hygiene',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio3',
        name: 'personal3',
         
        label: 'Uniforms, Shoes, ID Card',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio4',
        name: 'personal4',
         
        label: 'Staff Turnover, Absenteeism, Late Coming',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio5',
        name: 'personal5',
         
        label: 'Staff knowledge and responsiveness',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];

 export const cleaningandHygieneData=[
    {
        id: 'radio6',
        name: 'cleaning1',
         
        label: 'Cleaning of premises',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio7',
        name: 'cleaning2',
         
        label: 'Cleaning of Toilets',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio8',
        name: 'cleaning3',
         
        label: 'Judicious use of Housekeeping material',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio9',
        name: 'cleaning4',
         
        label: 'Documentation of tasks (todo & completed)',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio10',
        name: 'cleaning5',
         
        label: 'Suitable Garbage Disposal Measures',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ]

 export const siteSupervisionData=[
    {
        id: 'radio11',
        name: 'supervision1',
         
        label: 'Supervision Standards',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio12',
        name: 'supervision2',
         
        label: 'Job Knowledge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio13',
        name: 'supervision3',
         
        label: 'Speed, Efficiency, Work quality of site incharge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio14',
        name: 'supervision4',
         
        label: 'Responsiveness To Customer Needs',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio15',
        name: 'supervision5',
         
        label: 'End User Feedback',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];

 export const purchaseandStoresData=[
    {
        id: 'radio16',
        name: 'purchase1',
         
        label: 'Control of Delivery and Damages',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio17',
        name: 'purchase2',
         
        label: 'Level of Stocking',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio18',
        name: 'purchase3',
         
        label: 'Bin Card, Daily Indent System Being Followed',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio19',
        name: 'purchase4',
         
        label: 'Purchase Specifications Being Followed',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio20',
        name: 'purchase5',
         
        label: 'Quality of Material Supplied',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
 ];
export const controlsData=[
    {
        id: 'radio21',
        name: 'controls1',
         
        label: 'Appropriate documentation and Billing',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio22',
        name: 'controls2',
         
        label: 'Attendance and other relevant documents submitted on time',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio23',
        name: 'controls3',
         
        label: 'Regular trainings held (on-site / off-site)',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio24',
        name: 'controls4',
         
        label: 'Recommendation on preventive maintenance',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio25',
        name: 'controls5', //need to ask
         
        label: 'Timely receipt of materials',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
];

export const hoandTeamManagersData=[
    {
        id: 'radio26',
        name: 'ho1',
         
        label: 'Management team in regular contact',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio27',
        name: 'ho2',
         
        label: 'Supervision and Knowledge',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio28',
        name: 'ho3',
         
        label: 'Responsiveness to Client\'s Needs',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio29',
        name: 'ho4',
         
        label: 'Recommendation on new technology',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      },
      {
        id: 'radio30',
        name: 'ho5',
         
        label: 'Provide timely documentation and information',
        value1:1,
        value2:2,
        value3:3,
        value4:4,
        value5:5,
        radioLabel1: '5',
        radioLabel2: '4',
        radioLabel3: '3',
        radioLabel4: '2',
        radioLabel5: '1',
      }
];



